plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.youtubedownloader'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.youtubedownloader'
        minSdk 19
        targetSdk 28
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
}
